server:
  port: 1977

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5060/patternatlas
    url: jdbc:postgresql://localhost:5432/patternatlas
    #username: patternatlas
    username: postgres
    #password: patternatlas
    password: pattern
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create #update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      password: pass
      name: user

security:
  oauth2:
    resource:
      #      user-info-uri: http://localhost:8081/userinfo
      #      token-info-uri: http://localhost:8081/oauth/check_token
      jwk:
        key-set-uri: http://localhost:8081/.well-known/jwks.json

